---

# Set up a Fedora Workstation.
# My first major effort with Ansible playbooks.

- hosts: "{{ variable_host | default('all') }}"
  # Example to override 'all' grouping: --extra-vars "variable_host=127.0.0.1"

  vars:
    # Maximum version of Fedora that supports the freerdp-nightly repository
    # A check is necessary because the repository is not present immediately after the launch of a new Fedora version.
    # For example, the fedora-28 repository did not exist as of 2018-05-04.
    # This variable makes for an easy toggle.
    # Also track the minimum of nightly build used by the FreeRDP team.
    freerdp_nightly_min_version: "28"
    freerdp_nightly_max_version: "29"

    google_repo:
      name: "google-chrome"
      url: "http://dl.google.com/linux/chrome/rpm/stable/$basearch"
      gpgkey:
        src: "https://dl.google.com/linux/linux_signing_key.pub"
        dest: "/etc/pki/rpm-gpg/google_linux_signing_key.pub"

    skype_repo:
      name: "skype-stable"
      url: "https://repo.skype.com/rpm/stable/"
      gpgkey:
        src: "https://repo.skype.com/data/SKYPE-GPG-KEY"
        dest: "/etc/pki/rpm-gpg/SKYPE-GPG-KEY"

  environment:
    ANSIBLE: 1

  tasks:

  - name: Install Repositories (Fedora)
    become: yes
    when: (ansible_distribution == "Fedora")
    block:

      - name: "rpmfusion gpg keys for fedora {{ ansible_distribution_major_version }}"
        get_url:
          url: "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-{{ item }}-fedora-{{ ansible_distribution_major_version }}"
          dest: "/etc/pki/rpm-gpg/RPM-GPG-KEY-rmpfusion-{{ item }}-fedora-{{ ansible_distribution_major_version }}"
          owner: "root"
          group: "root"
        with_items:
          - "free"
          - "nonfree"

      - name: "rpmfusion repositories"
        yum_repository:
          name: "fedora-rpmfusion-{{ item }}"
          description: "RPMFusion ({{ item }})"
          baseurl: "http://download1.rpmfusion.org/{{ item }}/fedora/releases/$releasever/Everything/$basearch/os/"
          metalink: "https://mirrors.rpmfusion.org/metalink?repo={{ item }}-fedora-$releasever&arch=$basearch"
          gpgcheck: yes
          gpgkey: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rmpfusion-{{ item }}-fedora-{{ ansible_distribution_major_version }}"
          ip_resolve: 4
        with_items:
          - "free"
          - "nonfree"

      - name: freerdp-nightly repository
        when: ansible_distribution_major_version <= freerdp_nightly_max_version and ansible_distribution_major_version >= freerdp_nightly_min_version
        yum_repository:
          name: freerdp-nightly
          description: freerdp-nightly
          baseurl: https://pub.freerdp.com/repositories/rpm/fedora/$releasever/freerdp-nightly/
          metadata_expire: 43200 # 12 hours
          ip_resolve: 4
          gpgcheck: no

      - name: "install google gpg key"
        become: yes
        get_url:
          url: "{{ google_repo.gpgkey.src }}"
          dest: "{{ google_repo.gpgkey.dest }}"
          owner: "root"
          group: "root"

      - name: "{{ google_repo.name }} repository"
        become: yes
        yum_repository:
          name: "{{ google_repo.name }}"
          description: "{{ google_repo.name }}"
          baseurl: "{{ google_repo.url }}"
          gpgcheck: yes
          gpgkey: "file://{{ google_repo.gpgkey.dest }}"

      - name: "install {{ skype_repo.name }} gpg key"
        become: yes
        get_url:
          url: "{{ skype_repo.gpgkey.src }}"
          dest: "{{ skype_repo.gpgkey.dest }}"
          owner: "root"
          group: "root"

      - name: "{{ skype_repo.name }} repository"
        become: yes
        yum_repository:
          name: "{{ skype_repo.name }}"
          description: "{{ skype_repo.name }}"
          baseurl: "{{ skype_repo.url }}"
          gpgcheck: yes
          gpgkey: "file://{{ skype_repo.gpgkey.dest }}"

  - name: Install Fedora Packages
    # Some Fedora checks are a bit redundant in this version.
    when: (ansible_distribution == "Fedora")
    block:
      # Restrict to Fedora systems for the time being.
      # Support for other RedHat-based distributions can be added pending testing.
      - name: "Confirm DNF System"
        fail: msg="DNF not our primary package manager."
        when: not (ansible_pkg_mgr == "dnf")

      ## Development Tools and CLI items

      - name: install/update development tools and cli items
        dnf: name={{item}} state=latest
        become: yes
        with_items:
          - vim      # vim editor
          - tmux     # tmux multiplexer
          - svn      # Subversion version control
          - git      # Git version control
          - astyle   # Artistic Style code formatter
          - wget     # Network downloaded
          - curl     # URL Handler
          - python   # Python
          - python3  # Python v3

      - name: install/update fun cli items
        dnf: name={{item}} state=latest
        become: yes
        with_items:
          - mpg123 # Play sounds from the command line

      - name: install/update standard packages
        # Make sure that some boring common packages are up to date.
        dnf: name={{item}} state=latest
        become: yes
        with_items:
          - sed
          - tar
          - bash
          - coreutils
          - unzip
          - zip
          - fuse-exfat

      - name: install/update the 'development-tools' package group
        become: yes
        dnf: name='@development-tools' state=latest
        # Install failed when run against a Fedora 25 machine due to a module problem.
        # F25 is already EoL at time of writing anyways (2018-05-01, Ansible 2.4.1), so this is not a major concern.
        # Tested on:
        #   F25->F27 (Success)
        #   F25->F25 (FAIL)
        #   F26->F25 (FAIL)
        #   F26->F26 (Success)
        # Possibly related to https://github.com/ansible/ansible/issues/26868.
        when: (ansible_distribution == "Fedora" and ansible_distribution_version >= "26")

      ## Network-Based Items
      - name: install/update network utilities
        become: yes
        dnf: name={{item}} state=latest
        with_items:
          - nmap             # Network discovery
          - nmap-ncat        # Network Swiss Army Knife
          - wireshark        # Packet Captures
          - tcpdump          # Packet Captures
          - openconnect      # OpenConnect VPN (compatible with Cisco AnyConnect)
          - vpnc-script      # Used by openconnect
          - openvpn          # OpenVPN
          - openssh-clients  # SSH Client
          - openssh-server   # SSH Server
          - openssl          # OpenSSL
          - iperf3           # iperf3 Network Benchmarking

      ## Desktop Items

      - name: install/update desktop machine packages
        become: yes
        dnf: name={{item}} state=latest
        with_items:
          - conky               # Desktop information display
          - firefox             # Web Browser
          - google-chrome       # Fallback Web Browser
          - geany               # Code Editor
          - geany-themes        # Extra colour layouts for geany
          - tigervnc            # VNC Client
          - x11vnc              # Ad-Hoc VNC Server
          - slick-greeter       # Really neat-looking greeter (originated with Ubuntu?)
          - skypeforlinux       # Chat client
          - wireshark-gtk       # Wireshark GUI
          - libreoffice-calc    # Spreadsheets
          - libreoffice-writer  # Word
          - libreoffice-impress # Slideshows
          - NetworkManager      # Network Management Service
          - wine                # Windows compatibility

      - name: install/update freerdp-nightly
        become: yes
        dnf: name=freerdp-nightly state=latest # RDP Client
        when: ansible_distribution_major_version <= freerdp_nightly_max_version and ansible_distribution_major_version >= freerdp_nightly_min_version

      # Remove Default Greeter for Fedora MATE spin
      - name: remove lightdm-gtk greeter
        dnf: name=lightdm-gtk state=absent
        become: yes

      # Tidy Up
      - name: check dnf version
        shell: warn=false dnf --version | head -n1
        register: dnf_check
        changed_when: false # Never announce as changed.

      - name: Autoremove unneeded packages installed as dependencies
        become: yes
        dnf: autoremove=yes
        # Requires DNF v2.0.1 or greater.
        # 'version_compare' was renamed to 'version' with Ansible 2.5.
        # However, the old 'version_compare' name is still available with no apparent strings attached.
        when: (dnf_check.stdout and dnf_check.stdout is version_compare('2.0.1', '>='))

  - name: openssh service enabled
    become: yes
    service: name="sshd" state="started" enabled="yes"
