---
# Setup playbook for playing on a fresh Raspbian system.
# Includes commonly used packages and some light utilities.

- hosts: "{{ variable_host | default('all') }}"
  # Example to override 'all' grouping: --extra-vars "variable_host=127.0.0.1"

  vars:

    raspbian_packages:
      - tmux
      - vim
      - git
      - subversion
      - openvpn
      - nmap
      - unzip
      - zip
      - lm-sensors

  remote_user: pi

  tasks:
    - name: abort if not raspbian
      when: (ansible_lsb and ansible_lsb.id != "Raspbian")
      fail: msg="Non-Raspbian distribution - {{ ansible_os_family }} ({{ ansible_distribution }})"

    - name: install packages
      become: yes
      apt: name="{{ raspbian_packages }}" state="present"

    - name: apt update
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: apt upgrade
      become: yes
      apt:
        upgrade: safe
