---
# Setup playbook.
# Contains additional packages for a Raspbian system meant more as a dev staging area.
# Meant to be used on top of standard Raspbian playbook.

- hosts: "{{ variable_host | default('all') }}"
  # Example to override 'all' grouping: --extra-vars "variable_host=127.0.0.1"

  vars:

    raspbian_packages:
      - ansible

  remote_user: pi

  tasks:
    - name: abort if not raspbian
      when: (ansible_lsb and ansible_lsb.id != "Raspbian")
      fail: msg="Non-Raspbian distribution - {{ ansible_os_family }} ({{ ansible_distribution }})"

    - name: install packages
      become: yes
      apt: name="{{ raspbian_packages }}" state="present"

