---

- hosts: all

  vars:

    git:
      src: git://git.libav.org/libav.git
      dest: "{{ ansible_user_dir }}/.local/ansible-deployments/libav"

    x264:
      src: git://git.videolan.org/x264.git
      dest: "{{ ansible_user_dir }}/.local/ansible-deployments/x264"

    packages_redhat:
      # TODO: Confirm that the package list is complete.
      - gcc
      - make
      - lame-devel
      - libvorbis-devel
      - yasm

    packages_fedora:
      - x264-devel

    packages_x264:
      - nasm

  tasks:
    - name: install redhat dependencies (dnf)
      become: yes
      when: ansible_pkg_mgr == "dnf"
      dnf: name="{{ packages_redhat }}" state="latest"

    - name: install fedora dependencies (dnf)
      become: yes
      when: ansible_pkg_mgr == "dnf"
      dnf: name="{{ packages_fedora }}" state="latest"

    - name: install redhat dependencies (yum)
      become: yes
      when: ansible_pkg_mgr == "yum"
      yum: name="{{ packages_redhat }}" state="latest"

    - name: install x264 dependencies (yum)
      become: yes
      when: ansible_pkg_mgr == "yum"
      yum: name="{{ packages_x264 }}" state="latest"

    - name: get x264 (centos)
      git:
        repo: "{{ x264.src }}"
        dest: "{{ x264.dest }}"
      notify: configure x264

    - name: get libav
      git:
        repo: "{{ git.src }}"
        dest: "{{ git.dest }}"
      notify: configure libav

  handlers:

    - name: configure x264
      shell: ./configure --enable-static --enable-shared --disable-lavf --disable-asm
      args:
        chdir: "{{ x264.dest }}"
      notify: clean x264

    - name: clean x264
      shell: make clean
      args:
        chdir: "{{ x264.dest }}"
      notify: build x264

    - name: build x264
      shell: make
      args:
        chdir: "{{ x264.dest }}"
      notify:
        - install x264
        - install x264 lib

    - name: install x264 lib
      become: yes
      shell: make install-lib-shared
      args:
        chdir: "{{ x264.dest }}"
      notify: configure libav

    - name: install x264
      become: yes
      shell: make install
      args:
        chdir: "{{ x264.dest }}"

    - name: configure libav
      shell: ./configure --enable-libmp3lame --enable-gpl --enable-nonfree --enable-libx264
      args:
        chdir: "{{ git.dest }}"
      notify: clean libav
      environment:
        PKG_CONFIG_PATH: /usr/local/lib/pkgconfig

    - name: clean libav
      shell: make clean
      args:
        chdir: "{{ git.dest }}"
      notify: build libav

    - name: build libav
      shell: make
      args:
        chdir: "{{ git.dest }}"
      notify: install libav

    - name: install libav
      become: yes
      shell: make install
      args:
        chdir: "{{ git.dest }}"
