---

# Install the public export of my core tools.
# Note: As with other Ansible playbooks (so far as I know),
#   the user's home directory will need to at least exist before the playbook is run.

- hosts: all

  vars:

    git:
      src: https://github.com/adeutscher/core-tools.git
      dest: "{{ ansible_user_dir }}/tools/core-tools"

  tasks:

    - name: get core-tools (public)
      git:
        repo: "{{ git.src }}"
        dest: "{{ git.dest }}"
      notify: run setup script

  handlers:

    - name: run setup script
      shell: ./scripts/setup/all.sh
      args:
        chdir: "{{ git.dest }}"
