---

- hosts: all

  vars:
    base_url: "http://apt.sw.be/redhat/el{{ ansible_distribution_major_version }}/en/$basearch"
    base_mirrors: "http://mirrorlist.repoforge.org/el{{ ansible_distribution_major_version }}/mirrors-"
    gpg_key:
      src: "https://raw.githubusercontent.com/repoforge/rpms/master/specs/rpmforge-release/RPM-GPG-KEY-rpmforge-dag"
      dest: "/etc/pki/rpm-gpg/RPM-GPG-KEY-rpmforge-dag"

  tasks:

    - name: install rpmforge gpg key
      become: yes
      get_url:
        url: "{{ gpg_key.src }}"
        dest: "{{ gpg_key.dest }}"
        owner: root
        group: root

    - name: "install rpmforge repositories"
      become: yes
      yum_repository:
        name: "{{ item.name }}"
        description: "{{ item.name }}"
        file: "rpmforge"
        enabled: yes
        baseurl: "{{ base_url }}/{{ item.base }}"
        mirrorlist: "{{ base_mirrors }}{{ item.name }}"
        gpgcheck: yes
        gpgkey: "file://{{ gpg_key.dest }}"
      with_items:
        - { base: "rpmforge", "name": "rpmforge" }
        - { base: "extras", "name": "rpmforge-extras" }
