---

# Disable firewalld on a RHEL-based system
# Made for and tested on CentOS 7 Minimal and Fedora Server 28.
# Note: This playbook wipes all currently present firewall rules.
#       DO NOT do this on a server that you consider to be remotely at risk,
#       unless you plan to IMMEDIATELY install custom rules on it.
# This playbook was created because I often prefer to apply my own firewall configurations instead of firewalld.

- hosts: "{{ variable_host | default('all') }}"
  # Example to override 'all' grouping: --extra-vars "variable_host=127.0.0.1"

  environment:
    ANSIBLE: 1

  vars:
    chains:
      - INPUT
      - OUTPUT
      - FORWARD

  tasks:

  - name: install preferred packages
    become: yes
    action: >
      {{ ansible_pkg_mgr }} name="iptables-services" state=latest

  - name: firewalld service disabled
    become: yes
    service: name="firewalld" state="stopped" enabled="no"

  - name: iptables service enabled
    become: yes
    service: name="iptables" state="started" enabled="yes"
    notify: set iptables policy

  handlers:
  - name: set iptables policy
    become: yes
    iptables:
      policy: ACCEPT
      chain: "{{ item }}"
    with_items: "{{ chains }}"

  - name: flush iptables rules
    become: yes
    iptables:
      flush: yes
      chain: "{{ item }}"
    with_items: "{{ chains }}"

  - name: save reminder
    debug:
     msg: "iptables rules cleared, but saved rules still exist in /etc/sysconfig/iptables. Manually run 'service iptables save' to make current settings persist after a reboot."
