---

# Install and run ntpdate

- hosts: "{{ variable_host | default('all') }}"
  # Example to override 'all' grouping: --extra-vars "variable_host=127.0.0.1"

  environment:
    ANSIBLE: 1

  vars:
    time_server: "{{ variable_server | default('pool.ntp.org') }}"

  tasks:

    - name: run time update
      become: yes
      block:

        - name: install package
          action: >
            {{ ansible_pkg_mgr }} name=ntpdate state=latest

        - name: run ntpdate
          shell: ntpdate {{ time_server }}
