#!/bin/sh
 
# Uncomment the following two lines for normal desktop:
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
#sh /etc/X11/xinit/xinitrc
 
xrdb $HOME/.Xresources
#xsetroot -solid grey
x-terminal-emulator -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" &
#x-window-manager &
# Fix to make GNOME work
export XKL_XMODMAP_DISABLE=1
#/etc/X11/Xsession
#exec /usr/bin/gnome-session --session=gnome-classic &
gnome-session --session=gnome-fallback &

