---

- hosts: all

  vars:
    distro: "Fedora"
    version: "31"
    packages:
      main:
        - dotnet-runtime-2.1
        - dotnet-sdk-3.1

      other:
        # libunwind is used to run one of my projects.
        # Some Googling suggests that this is not an uncommon requirement, so I am including it here.
        - libunwind

  tasks:

  - name: "fail if not on the right fedora version"
    when: (ansible_distribution != distro) or (ansible_distribution_version < version)
    fail: msg="Must only run on {{ distro }} (Minimum version{{ ":" }} {{ version }})"

  - name: "install microsoft rpm key"
    become: yes
    rpm_key:
      key: https://packages.microsoft.com/keys/microsoft.asc
      state: present

  - name: "install microsoft production repo"
    become: yes
    get_url:
      url: https://packages.microsoft.com/config/fedora/{{ version }}/prod.repo
      dest: /etc/yum.repos.d/microsoft-prod.repo
      mode: 0644

  - name: "install .net core packages"
    become: yes
    dnf:
      name: "{{ packages.main }}"
      state: latest

  - name: "install other items"
    become: yes
    dnf:
      name: "{{ packages.other }}"
      state: latest

