---

- hosts: all

  vars:
    distro: "CentOS"
    version: "7"

  tasks:

  - name: "fail if not centos {{ version }}"
    when: ansible_distribution != distro or ansible_distribution < version
    fail: msg="Must only run on {{ distro }} (Minimum version{{ ":" }} {{ version }})"

  - name: "install microsoft repository"
    become: yes
    yum:
      name: https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm
      state: latest

  - name: "install .net core 2.1"
    become: yes
    yum:
      name: aspnetcore-runtime-2.1
      state: latest

  - name: "install other items"
    become: yes
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
      # libunwind is used to run one of my projects.
      # Some Googling suggests that this is not an uncommon requirement, so I am including it here.
      - libunwind


