---

- hosts: all

  vars:
    distro: "Fedora"
    # Microsoft instructions for Fedora 28 specifically say to use the Fedora 27 repository link.
    #   A dedicated Fedora 28 repository does not exist at this time.
    version: 27

  tasks:

  - name: "fail if not fedora {{ version }}"
    when: ansible_distribution != distro or ansible_distribution < version
    fail: msg="Must only run on {{ distro }} (Minimum version{{ ":" }} {{ version }})"

  - name: "install microsoft rpm key"
    become: yes
    rpm_key:
      key: https://packages.microsoft.com/keys/microsoft.asc
      state: present

  - name: "install microsoft production repo"
    become: yes
    get_url:
      url: https://packages.microsoft.com/config/fedora/{{ version }}/prod.repo
      dest: /etc/yum.repos.d/microsoft-prod.repo
      mode: 0644

  - name: "install .net core 2.1"
    become: yes
    dnf:
      name: aspnetcore-runtime-2.1
      state: latest

  - name: "install other items"
    become: yes
    dnf:
      name: "{{ item }}"
      state: latest
    with_items:
      # libunwind is used to run one of my projects.
      # Some Googling suggests that this is not an uncommon requirement, so I am including it here.
      - libunwind

